= Demo-Dokumentation
Vorname Nachname <vorname.nachname@htw-dresden.de>
include::attributes.inc.adoc[]

Praktikumsbeispiel für die Verwendung von Diagrammen mit PlantUML in Asciidoctor.


== PlantUML-Diagramme

Diagramme mit der PlantUML-Notation können im Asciidoctor-Dokument direkt als Block *eingebettet* oder als externe Datei *inkludiert* werden.

=== Funktionstest

Ein Testdiagramm, ob die Vorschau in VS Code bzw. die Generierung mit Asciidoctor funktioniert.

.Testdiagramm
[plantuml, "{diagramsdir}/hello_world", svg]
....
actor Human
(\nWorld\n) #dff
note right of Human : Hello
....

.Graphiz Dot Test
[plantuml, "{diagramsdir}/testdot", svg]
....
@startuml
testdot
@enduml
....

Hinweise zur Einrichtung siehe zugehörige Aufgabenstellung.

=== Eingebettet

Ein Beispiel für ein direkt im Dokument eingebettetes PlantUML-Diagramm.

//titel der Grafik
.Klassendiagramm mit PlantUML
//Attribut für die Generierung mit der Asciidoctor-Diagramm Erweiterung
//Attribute: Diagramm-Type (Textsyntax), generierter Dateiname (inkl. Zielverzeichnis {diagramsdir}), Bildformat (png, svg)
[plantuml, "{diagramsdir}/syntax-example1", svg] 

//textliche Beschreibung (PlantUML Notation) des entsprechenden Diagramm-Types
....
class Graphic 
interface Shape <<Interface>> {
  draw()
}
class Circle
class Triangle
class Square
class Quader
class "Class A" as c1
class "Class B" as c2

Graphic -> Shape
Shape <|.. Circle
Shape <|.. Triangle
Shape <|.. Square
Shape <|.. Quader

c1 -- c2
....
// .... definieren einen Block
// es sind maximal zwei classen verbunden werden
// <|.. ist getrichelte Linie
// -> sind durchgehende Linien 
// -- verbindet zwei classen durch eine Linie
// weiteres https://plantuml.com/de/class-diagram

=== Inkludiert

Ein Beispiel für ein im Dokument inkludiertes PlantUML-Diagramm als externe Datei.

.Klassendiagramm mit PlantUML
[plantuml, "{diagramsdir}/syntax-example2", svg]
....
include::{plantumlsdir}/syntax-example2.puml[]
....


.Klassendiagramm mit PlanUML
[plantuml, "{diagramsdir}/syntax-C4Model_layer1", svg]
....
include::{plantumlsdir}/C4Model_layer1.puml[]
....
